version: 2

# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
          timezone: "Asia/Tokyo"
      open-pull-requests-limit: 99
      labels:
          - A-dependency
          - I-dependency-gardening
      versioning-strategy: increase
      groups:
          ava:
              patterns:
                  - ava
                  - "@ava/typescript"
          react:
              patterns:
                  - react
                  - react-dom
          "react d.ts":
              patterns:
                  - "@types/react"
                  - "@types/react-dom"
          babel:
              patterns:
                  - "@babel/*"
          rollup:
              patterns:
                  - rollup
                  - "@rollup/*"
          eslint:
              patterns:
                  - eslint
                  - "@eslint/*"
          typescript-eslint:
              patterns:
                  - "@typescript-eslint/*"

    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: weekly
      open-pull-requests-limit: 99
      labels:
          - A-dependency
          - I-dependency-gardening

    #####################################################
    #   In-repository composite actions
    #####################################################
    - package-ecosystem: github-actions
      directory: "/.github/actions/setup_ci/"
      schedule:
          interval: weekly
      open-pull-requests-limit: 99
      labels:
          - A-dependency
          - I-dependency-gardening
