version: 2

# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    labels:
      - A-dependency
      - I-dependency-gardening
    versioning-strategy: increase
