version: 2

# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
          timezone: "Asia/Tokyo"
      open-pull-requests-limit: 99
      labels:
          - A-dependency
          - I-dependency-gardening
      versioning-strategy: increase
      ignore:
          # Remove this ignore after return to react stable channel.
          - dependency-name: "react"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
          # Remove this ignore after return to react stable channel.
          - dependency-name: "react-dom"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
      groups:
          ava:
              patterns:
                  - ava
                  - "@ava/typescript"
          react:
              patterns:
                  - react
                  - react-dom
          "react d.ts":
              patterns:
                  - "@types/react"
                  - "@types/react-dom"
          babel:
              patterns:
                  - "@babel/*"
          rollup:
              patterns:
                  - rollup
                  - "@rollup/*"
          eslint:
              patterns:
                  - eslint
                  - "@eslint/*"
          turborepo:
              patterns:
                  - turbo
                  - eslint-plugin-turbo
          typescript-eslint:
              patterns:
                  - "@typescript-eslint/*"
          react-compiler:
              patterns:
                  - "babel-plugin-react-compiler"
                  - "eslint-plugin-react-compiler"

    - package-ecosystem: github-actions
      directories:
          - "/"
          - "/.github/actions/setup_ci/"
      schedule:
          interval: weekly
      open-pull-requests-limit: 99
      labels:
          - A-dependency
          - I-dependency-gardening
