version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 99
  labels:
  - A-dependency
  - I-dependency-gardening
  versioning-strategy: increase
