# https://prettier.io/docs/en/configuration.html

semi = true
singleQuote = true
tabWidth = 4
useTabs = false

[[overrides]]
    files = "*.css"
    [overrides.options]
    printWidth = 256

[[overrides]]
    files = [
        "*.yml",
        "*.yaml",
    ]
    [overrides.options]
    singleQuote = false
