name: Setup CI
description: Setup CI environment

runs:
    using: composite
    steps:
        - uses: actions/setup-node@v4
          with:
              node-version: 22.x
        - name: Setup corepack
          shell: bash
          run: |
              make setup_corepack
        - name: Get package manager's cache directory
          id: npm-cache-dir
          shell: bash
          run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
        - name: cache dependencies
          uses: actions/cache@v4
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
              path: ${{ steps.npm-cache-dir.outputs.dir }}
              key: build-v1-${{ runner.os }}-node-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  build-v1-${{ runner.os }}-node-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        - name: install dependencies
          shell: bash
          # We only cache `npm config get cache`, not including `node_modules/`.
          # thus we need to do `npm ci` to restore `node_modules/` so we need run always this step.
          # if: steps.npm-cache.outputs.cache-hit != 'true''
          run: |
              make install
