name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: cache dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: build-v0-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

    - name: install dependencies,
      run: |
        yarn install

    - name: build
      run: make build -j

    - name: check fmt
      run: make fmt -j

    - name: check diff
      run: make git_diff -j

    - name: test
      run: make test -j
      env:
        CI: true
