name: CI

on: push

jobs:
    install_dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup_ci
              with:
                  node-version: 17.x

    build:
        needs: [install_dependencies]
        uses: ./.github/workflows/ci_actual_action.yaml
        with:
            node-version: 17.x
            subcommand: build_production

    build_by_esbuild:
        continue-on-error: true
        needs: [install_dependencies]
        uses: ./.github/workflows/ci_actual_action.yaml
        with:
            node-version: 17.x
            subcommand: build_package
            makeflags: USE_ESBUILD=1
            cwd: ./packages/linkplaces

    lint:
        needs: [install_dependencies]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup_ci
              with:
                  node-version: 17.x
            - name: Lint
              run: make lint -j
              env:
                  CI: true

    check_type_integrity:
        needs: [install_dependencies]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup_ci
              with:
                  node-version: 17.x
            - name: typecheck
              run: make typecheck -j
              env:
                  CI: true

    check_formatting:
        needs: [install_dependencies]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup_ci
              with:
                  node-version: 17.x
            - name: check formatting
              run: make check_format -j
              env:
                  CI: true

    unittest:
        needs: [install_dependencies]
        uses: ./.github/workflows/ci_actual_action.yaml
        with:
            node-version: 17.x
            subcommand: unittest
            cwd: ./packages/linkplaces
