name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node-version }}

    - name: cache dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: build-v0-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

    - name: install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: build
      run: make build -j

    - name: check formatting
      run: make check_fmt -j

    - name: test
      run: make test -j
      env:
        CI: true
