name: CI on main branch

on:
    push:
        branches:
            - "main"

# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
    # We would like to run this workflow for all commits in the target branch.
    # But we need to limit the workflow concurrency to ensure a deployment order as FIFO.
    #
    # If we use `${{ github.workflow }}-${{ github.ref }}` and the invoked workflow for our `ci` job also has same group id,
    # this workflow will be cancelled by the invoked workflow's `concurrency` setting.
    # To avoid this problem, we use uuid v4 as a key to mark this workflow's uniqueness.
    group: "02c19fdb-ba39-4da8-99a0-b481b4a56f2b"

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml
