name: Detect unmergeable PRs

on:
    push:
        branches:
            - "*"
        # Ignore all pushing for tags
        tags:
            - "!*"
    # If you'd like to remove the added label by this action automatically
    # on updating a pull request by pushing changes.
    # Please recieve this event.
    pull_request:
        types: synchronize

permissions:
    pull-requests: write

jobs:
    detect_unmergeable_pull_request_and_mark_them:
        runs-on: ubuntu-latest
        permissions:
            contents: none
            pull-requests: write
        steps:
            - name: Dump GitHub Context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "${GITHUB_CONTEXT}"
            - name: Run the action to detect unmergeable PRs
              uses: tetsuharuohzeki/github-action-detect-unmergeable@620b042230a7e447af95e5e5d46320197f84499b
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
